language: java
jdk:
- oraclejdk8
install: true
script:
- gradle zipMap
before_deploy:
- git config --global user.email "tripleabuilderbot@gmail.com" 
- git config --global user.name "tripleabuilderbot"
- export MAP_TAGGED_VERSION="$MAP_VERSION.$TRAVIS_BUILD_NUMBER"
- git tag $MAP_TAGGED_VERSION -a -m "$MAP_TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-maps/$REPO_NAME --tags
deploy:
  provider: releases
  api_key:
    secure: mNhGtY2SuPV0d4dU4F9xgo0H8M1KbPIw6mQIdg3xLtSYH1rYIpl3eQfyQamVA7mu2s31ujSF6s7avn5f0u3qEZdBamH7MJiJKSd2W9rLpBjF5D8RrKMYMVqtipJsoiaa71NZAsZk7z9cFZc/hB8GzDq2T3L0FLowfKbG4+UPWMgGAOdLbBrTMxrhRrNyLO9QQk7fxR8SMMt4heRkoD9jHN1xX9/3ygVgj/qo19h65g3rL76Y7cGt7/sTVSYmw/ey3dvtgPj4hPjmO/GGhESJnSaNm1NYa9Pdg5758qgZnWM+eBnjsRblKsSURsI7LyKKcnXJXP0KxrYa0DYwKFwrghXInRdTIEJeradxIvtbiwYfgLNbmyLV+taXL+qBuOmaKpmN4WUpflMMBGdWRdRkisAkTLGCJNUZ2jUk0PnZKUumm/p6rs8M0kfy1YyAYinUMhmHDiG7y08HFSXXi/3FnLTxZTDAMCDGn5t4s0aSc21qfkgWvRxI8OhN/DpHCnsJ/o9nxz2P81nkOpM0ypeauGMYQVBzw6O/hkKAp8CLDXlKglzUhDMLbQeDiuOOpSX/U0KoX9ElqGzs+9hAPPhj8rPLhlyGVkIRqHZa9HYZUyheDqCuJnP5WPS37slcPWSEH9Y8gLE7CUIolc6wQjKCy+OkVVtiIgAHERFMepuRJ9M=
  file: "$REPO_NAME.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    all_branches: true
